### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by popaprozac** [maxkfranz/weaver#25]
Attempted to run require a function into a thread and get this output. I have attempted to run the examples in the docs but always get this error.

Thanks in advance.

**Comment by maxkfranz** [comment]
The tests and the demos on the docs are working for this, so please provide an example.

**Comment by popaprozac** [comment]
To give more context, I copied this from the docs:

```
function foo(){
  return 'bar';
}

var t = weaver.thread();

t.require( foo, 'foo' ); // explicitly specify name to avoid minification issues

t.run(function(){
   // explicitly get by reference to avoid minification issues:
  var foo = _ref_('foo');
  var resolve = _ref_('resolve');

  resolve( foo() );
}).then(function( val ){
  console.log( val ); // bar
});
```

I attempt to run this code from a meteor method or from inside meteor.startup

Edit: Didn't mean to close!
